#! /bin/sh

# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"
