#! /bin/sh

# Window borders (Auto-Generate)
bspc config focused_border_color "#5e6574"
bspc config normal_border_color "#272a34"

bspc config active_border_color "#5e6574"
bspc config presel_feedback_color "#272a34"
