#! /bin/sh

# Window borders (Auto-Generate)
bspc config focused_border_color "#81A1C1" #50864c4
bspc config normal_border_color "#262626"

bspc config active_border_color "#81A1C1"
bspc config presel_feedback_color "#262626"
