#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

# fix some Java applications
# wmname LG3D


# workspaces

bspc monitor primary -d 1 2 3 4 5 6 7
bspc monitor LVDS-1 -d 7  # TODO: multiple monitors

bspc config focus_follows_pointer true

#
# Themes
#

#~/.config/bspwm/themes/bspwm_catppuccin/bspwmrc
#~/.config/bspwm/themes/bspwm_gruvbox/bspwmrc
~/.config/bspwm/themes/bspwm_dark/bspwmrc

bspc config border_width 3
bspc config borderless_monocle true


# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 10

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


# rules

bspc rule -a feh state=floating rectangle=1600x1100+460+80
bspc rule -a Thunar state=floating rectangle=1600x900+460+200
bspc rule -a pavucontrol state=floating rectangle=970x600+970+70
#bspc rule -a firefox desktop='^6'

# python script to always initialize with a different wallpaper:
# TODO: Add loading of basic scripts

#~/.config/bspwm/scripts/launch.sh &
~/.config/polybar/launch.sh

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker and redshift
#pgrep -x redshift > /dev/null || redshift &

# start compositor
picom --config $HOME/.config/bspwm/picom_configurations/1.conf &

# autostart
flameshot &
#firefox &
#redshift &
#nitrogen &
