[colors.bright]
black = "#666666"
blue = "#6699cc"
cyan = "#00ccff"
green = "#2be491"
magenta = "#ff80b2"
red = "#ff8080"
white = "#cccccc"
yellow = "#ff9955"

[colors.cursor]
cursor = "#cccccc"
text = "#272a34"

[colors.dim]
black = "#23252e"
blue = "#6699cc"
cyan = "#00ccff"
green = "#2be491"
magenta = "#ff80b2"
red = "#ff8080"
white = "#7f7f7f"
yellow = "#ff9955"

[colors.hints.end]
background = "#cccccc"
foreground = "#272a34"

[colors.hints.start]
background = "#ff9955"
foreground = "#272a34"

[colors.normal]
black = "#23252e"
blue = "#6699cc"
cyan = "#00ccff"
green = "#2be491"
magenta = "#ff80b2"
red = "#ff8080"
white = "#cccccc"
yellow = "#ff9955"

[colors.primary]
background = "#272a34"
bright_foreground = "#f9f9f9"
dim_foreground = "#cccccc"
foreground = "#f9f9f9"

[colors.search.focused_match]
background = "#2be491"
foreground = "#272a34"

[colors.footer_bar]
background = "#cccccc"
foreground = "#272a34"

[colors.search.matches]
background = "#cccccc"
foreground = "#272a34"

[colors.selection]
background = "#ff80b2"
text = "#272a34"

[colors.vi_mode_cursor]
cursor = "#6699cc"
text = "#272a34"
