#! /bin/sh

# Window borders (Auto-Generate)
bspc config focused_border_color "#83A598"
bspc config normal_border_color "#1D2021"

bspc config active_border_color "#83A598"
bspc config presel_feedback_color "#1D2021"
