#! /bin/sh

# Window borders (Auto-Generate)
bspc config focused_border_color "#b8bb26"
bspc config normal_border_color "#282828"

bspc config active_border_color "#fe8019"
bspc config presel_feedback_color "#b8bb26"
